"""SQLAlchemy declarative base and shared mixins.

Kept separate from `session.py` so that model modules (added in future
sprints) can import `Base` without pulling in engine/session machinery —
respecting the Interface Segregation Principle.
"""

from __future__ import annotations

import datetime as dt

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming convention keeps autogenerated Alembic migrations stable
# and constraint names predictable across databases.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Base class for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds `created_at` / `updated_at` columns to a model.

    Purely opt-in via multiple inheritance, e.g.:
        class Trade(Base, TimestampMixin): ...
    """

    created_at: Mapped[dt.datetime] = mapped_column(
        server_default=func.now(), nullable=False
    )
    updated_at: Mapped[dt.datetime] = mapped_column(
        server_default=func.now(), onupdate=func.now(), nullable=False
    )
